-- AlterEnum: Add PARTIALLY_DELIVERED and DELIVERED to StockRequestStatus
ALTER TYPE "StockRequestStatus" ADD VALUE IF NOT EXISTS 'PARTIALLY_DELIVERED';
ALTER TYPE "StockRequestStatus" ADD VALUE IF NOT EXISTS 'DELIVERED';
